"""Automated GitHub Pull Request creation integrating Mermaid diagrams and CI quality reports."""

from __future__ import annotations

import logging
from typing import Any

from github import Github
from pydantic import BaseModel

from src.ci.report import CIReport
from src.config import settings
from src.gitops.git_client import GitClient

logger = logging.getLogger(__name__)


class GitOpsResult(BaseModel):
    """Result of GitOps branch creation, commit, push, and Pull Request opening."""

    branch_name: str
    commit_sha: str
    pr_number: int | None = None
    pr_url: str | None = None
    status: str = "success"  # "success", "rejected", "failed"
    title: str = ""
    body: str = ""


class GitHubPRManager:
    """Manages GitHub operations and Pull Request creation."""

    def __init__(
        self,
        token: str | None = None,
        repository: str | None = None,
        base_branch: str | None = None,
        git_client: GitClient | None = None,
    ):
        self.token = token or settings.github_token
        self.repository_name = repository or settings.github_repository
        self.base_branch = base_branch or settings.github_base_branch
        self.git_client = git_client or GitClient()

    def build_pr_body(
        self,
        product_name: str,
        files: dict[str, str],
        ci_report: CIReport,
        diagram_md: str = "",
    ) -> str:
        """Build a comprehensive PR markdown body embedding Mermaid and CI report."""
        lines = [
            f"# Data Product: {product_name.replace('-', ' ').title()}",
            "",
            "## Summary",
            f"Automated pipeline generated by **Databricks Steward Agent** for data product `{product_name}`.",
            "",
            "### Modified / Created Artifacts",
        ]
        for f in files:
            lines.append(f"- `{f}`")

        if diagram_md.strip():
            lines.extend(
                [
                    "",
                    "### Architectural & Semantic Lineage Diagram",
                    "```mermaid",
                    diagram_md.strip(),
                    "```",
                ]
            )

        lines.extend(
            [
                "",
                "### CI Quality Gate Summary",
                ci_report.summary_markdown or ci_report.format_markdown(),
                "",
                "---",
                "*Automated by Databricks Steward Agent with GitOps integration.*",
            ]
        )

        return "\n".join(lines)

    def create_data_product_pr(
        self,
        product_name: str,
        files: dict[str, str],
        ci_report: CIReport,
        diagram_md: str = "",
        base_branch: str | None = None,
        dry_run: bool = False,
        repo: Any | None = None,
    ) -> GitOpsResult:
        """Execute full GitOps cycle: branch, commit, push, and open GitHub PR.

        Args:
            product_name: Name of data product (used for branch name and PR title).
            files: Dictionary mapping file paths to file contents.
            ci_report: CIReport object from the CI pipeline runner.
            diagram_md: Optional Mermaid diagram code string.
            base_branch: Target base branch (default: self.base_branch).
            dry_run: If True, simulates GitHub API PR creation.
            repo: Optional PyGithub Repository mock or instance.

        Returns:
            GitOpsResult containing PR metadata and status.
        """
        # Guard: Check CI approval
        if not ci_report.is_approved:
            logger.warning("Rejecting PR creation: CI quality gate has not approved the code.")
            return GitOpsResult(
                branch_name="",
                commit_sha="",
                status="rejected",
                title="",
                body="CI quality gate rejected the pipeline. PR was not opened.",
            )

        target_base = base_branch or self.base_branch
        orig_branch_res = self.git_client._run_git(["rev-parse", "--abbrev-ref", "HEAD"])
        orig_branch = (
            orig_branch_res.stdout.strip()
            if orig_branch_res.returncode == 0 and orig_branch_res.stdout.strip()
            else None
        )

        branch_name = self.git_client.create_feature_branch(product_name, base_branch=target_base)

        commit_title = f"feat(data-product): add {product_name} pipeline"
        commit_sha = self.git_client.commit_files(
            branch_name=branch_name,
            files=files,
            message=commit_title,
        )

        # Restore original branch if it was modified
        if orig_branch and orig_branch != branch_name:
            self.git_client._run_git(["checkout", orig_branch])

        pr_title = f"feat(data-product): implement {product_name} data product"
        pr_body = self.build_pr_body(
            product_name=product_name,
            files=files,
            ci_report=ci_report,
            diagram_md=diagram_md,
        )

        # Handle PR opening via PyGithub
        if dry_run or (not self.token and repo is None):
            logger.info("Operating in dry-run/mock mode. Simulating GitHub Pull Request.")
            repo_display = self.repository_name or "databricks/data-products"
            return GitOpsResult(
                branch_name=branch_name,
                commit_sha=commit_sha,
                pr_number=101,
                pr_url=f"https://github.com/{repo_display}/pull/101",
                status="success",
                title=pr_title,
                body=pr_body,
            )

        try:
            # Push the created branch to remote before opening PR
            self.git_client.push_branch(branch_name)

            target_repo = repo
            if target_repo is None:
                gh = Github(self.token)
                target_repo = gh.get_repo(self.repository_name)

            pull_request = target_repo.create_pull(
                title=pr_title,
                body=pr_body,
                head=branch_name,
                base=target_base,
            )

            return GitOpsResult(
                branch_name=branch_name,
                commit_sha=commit_sha,
                pr_number=getattr(pull_request, "number", 1),
                pr_url=getattr(
                    pull_request,
                    "html_url",
                    f"https://github.com/{self.repository_name}/pull/{getattr(pull_request, 'number', 1)}",
                ),
                status="success",
                title=pr_title,
                body=pr_body,
            )
        except Exception as e:  # noqa: BLE001
            logger.error(f"Failed to create GitHub PR via API: {e}")
            return GitOpsResult(
                branch_name=branch_name,
                commit_sha=commit_sha,
                status="failed",
                title=pr_title,
                body=f"Failed to open GitHub PR: {e}",
            )


def create_data_product_pr(
    product_name: str,
    files: dict[str, str],
    ci_report: CIReport,
    diagram_md: str = "",
    base_branch: str = "main",
    dry_run: bool = False,
    repo: Any | None = None,
) -> GitOpsResult:
    """Module-level entry point conforming to PROJECT.md interface contract."""
    manager = GitHubPRManager(base_branch=base_branch)
    return manager.create_data_product_pr(
        product_name=product_name,
        files=files,
        ci_report=ci_report,
        diagram_md=diagram_md,
        base_branch=base_branch,
        dry_run=dry_run,
        repo=repo,
    )
